### ISSUE TITLE
Clustered configuration not working

### ISSUE THREAD

**Issue by giuliopulina** [socketio/socket.io-redis-streams-adapter#10] opened 2024-02-09 07:56 UTC
I'm trying to configure the adapter to connect to a Redis cluster, but something is not working as expected.
Enabling DEBUG mode, I found the following error:

```
server-paul-1    | 2024-02-09T07:48:14.517Z socket.io-redis-streams-adapter publishing { uid: '5e7f12ae1e44536c', nsp: '/', type: 1 }
server-paul-1    | 2024-02-09T07:48:14.521Z socket.io-redis-streams-adapter something went wrong while consuming the stream: 
Cannot read properties of undefined (reading 'replicas')
```

Configuration of the Node server is the following one (omitting not relevant parts):

```
const express = require('express');
const app = express();
const httpServer = require("http").createServer(app);

const { Server } = require("socket.io");
const { createAdapter } = require('@socket.io/redis-streams-adapter');
const { createCluster } = require('redis');

const port = process.env.PORT || 3000;
const serverName = process.env.NAME || 'Unknown';

const server = httpServer.listen(port);
const cluster = createCluster({
    rootNodes: [
        {
            url: 'redis://173.18.0.8:6379'
        },
       {
            url: 'redis://173.18.0.9:6379'
        }
    ]
});

cluster.on('error', (err) => console.log('Redis Cluster Error', err));

(async () => {
   await cluster.connect();
   console.log('Connected to Redis cluster');
   const io = new Server(server, {
	  adapter: createAdapter(cluster),
	  connectionStateRecovery: {
		maxDisconnectionDuration: 2 * 60 * 1000,
		skipMiddlewares: true,
	  }
	});

	// Routing
	app.use(express.static(__dirname + '/public'));

	io.on('connection', socket => {
            [....] 
	});
})();
```

If needed, I can provide a sample project that reproduces the error.

**Comment by darrachequesne** [comment] 2024-02-13 07:25
I was indeed able to reproduce, I'm digging into this.

**Comment by darrachequesne** [comment] 2024-02-13 14:20
Actually, I was not able to reproduce: https://github.com/socketio/socket.io-redis-streams-adapter/commit/65d0539eb7eb9649845ee744a4de4e0646fa194e

I had to bump the version of `redis` from version `4.6.5` to `4.6.13` for passing the tests though, maybe that could explain your issue?

**Comment by darrachequesne** [comment] 2024-02-13 16:56
> Also it seems that the upgrade was not needed, as I saw that that the [package.json](https://github.com/socketio/socket.io-redis-streams-adapter/blob/65d0539eb7eb9649845ee744a4de4e0646fa194e/package.json#L39) version is still 4.6.5 and the CI is green 😉

The `package-lock.json` file has the actual version: https://github.com/socketio/socket.io-redis-streams-adapter/blob/65d0539eb7eb9649845ee744a4de4e0646fa194e/package-lock.json#L4530-L4531

You can check with:

```
$ npm ls redis
@socket.io/redis-streams-adapter@0.1.0 /git/socket.io/socket.io-redis-streams-adapter
└── redis@4.6.13
```

> Furthermore, I'm not even able to run "npm test" (I am on Windows machine) because it fails complaining about 'prettier' issues

Hmm, that's embarassing :innocent: , let's fix this.

> I think that there is something wrong with my docker-compose setup (especially related to network configuration)

That's weird indeed. Aren't you able to reach the Redis cluster from your machine?

```
$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED        STATUS        PORTS                                                                                                   NAMES
b7f00167e70a   grokzen/redis-cluster:7.0.10   "/docker-entrypoint.…"   24 hours ago   Up 24 hours   5000-5002/tcp, 6379/tcp, 7006-7007/tcp, 0.0.0.0:7000-7005->7000-7005/tcp, :::7000-7005->7000-7005/tcp   socketio-redis-streams-adapter-redis-cluster-1

$ redis-cli -p 7000
> CLUSTER NODES
8e3bab0b15383e553955a2655595c93e72d13cd1 172.25.0.3:7001@17001 master - 0 1707843298482 2 connected 5461-10922
99d21c816b0fbe97faddb193bbf735120f4d31d9 172.25.0.3:7002@17002 master - 0 1707843297476 3 connected 10923-16383
4e44c97984ba201907680edd79d1da63f7fdadfa 172.25.0.3:7003@17003 slave 1e58ca5e23d16c7b064161c23d9454ba0588036d 0 1707843299487 1 connected
c587517dc726f0380579e4cde696eeb78fbb0c36 172.25.0.3:7005@17005 slave 99d21c816b0fbe97faddb193bbf735120f4d31d9 0 1707843298582 3 connected
6d80ce083ee6a6e3800f6aa0c55313f635985715 172.25.0.3:7004@17004 slave 8e3bab0b15383e553955a2655595c93e72d13cd1 0 1707843297000 2 connected
1e58ca5e23d16c7b064161c23d9454ba0588036d 172.25.0.3:7000@17000 myself,master - 0 1707843298000 1 connected 0-5460
```

**Comment by giuliopulina** [comment] 2024-02-13 22:26
> > Also it seems that the upgrade was not needed, as I saw that that the [package.json](https://github.com/socketio/socket.io-redis-streams-adapter/blob/65d0539eb7eb9649845ee744a4de4e0646fa194e/package.json#L39) version is still 4.6.5 and the CI is green 😉
> 
> The `package-lock.json` file has the actual version:
> 
> https://github.com/socketio/socket.io-redis-streams-adapter/blob/65d0539eb7eb9649845ee744a4de4e0646fa194e/package-lock.json#L4530-L4531
> 
> You can check with:
> 
> ```
> $ npm ls redis
> @socket.io/redis-streams-adapter@0.1.0 /git/socket.io/socket.io-redis-streams-adapter
> └── redis@4.6.13
> ```
> 

You're right 👍 

> > Furthermore, I'm not even able to run "npm test" (I am on Windows machine) because it fails complaining about 'prettier' issues
> 
> Hmm, that's embarassing 😇 , let's fix this.
> 
> > I think that there is something wrong with my docker-compose setup (especially related to network configuration)
> 
> That's weird indeed. Aren't you able to reach the Redis cluster from your machine?
> 
> ```
> $ docker ps
> CONTAINER ID   IMAGE                          COMMAND                  CREATED        STATUS        PORTS                                                                                                   NAMES
> b7f00167e70a   grokzen/redis-cluster:7.0.10   "/docker-entrypoint.…"   24 hours ago   Up 24 hours   5000-5002/tcp, 6379/tcp, 7006-7007/tcp, 0.0.0.0:7000-7005->7000-7005/tcp, :::7000-7005->7000-7005/tcp   socketio-redis-streams-adapter-redis-cluster-1
> 
> $ redis-cli -p 7000
> > CLUSTER NODES
> 8e3bab0b15383e553955a2655595c93e72d13cd1 172.25.0.3:7001@17001 master - 0 1707843298482 2 connected 5461-10922
> 99d21c816b0fbe97faddb193bbf735120f4d31d9 172.25.0.3:7002@17002 master - 0 1707843297476 3 connected 10923-16383
> 4e44c97984ba201907680edd79d1da63f7fdadfa 172.25.0.3:7003@17003 slave 1e58ca5e23d16c7b064161c23d9454ba0588036d 0 1707843299487 1 connected
> c587517dc726f0380579e4cde696eeb78fbb0c36 172.25.0.3:7005@17005 slave 99d21c816b0fbe97faddb193bbf735120f4d31d9 0 1707843298582 3 connected
> 6d80ce083ee6a6e3800f6aa0c55313f635985715 172.25.0.3:7004@17004 slave 8e3bab0b15383e553955a2655595c93e72d13cd1 0 1707843297000 2 connected
> 1e58ca5e23d16c7b064161c23d9454ba0588036d 172.25.0.3:7000@17000 myself,master - 0 1707843298000 1 connected 0-5460
> ```

I managed to make npm test work on Windows 🎉 

One huge mistake I was making was that I didn't run docker-compose before running npm, because I was thinking that it was automatically run by npm test.

There are a couple of changes to be made to Redis configuration and to prettier in order to make everything work on Windows. I will create a PR tomorrow

**Comment by darrachequesne** [comment] 2024-02-21 14:49
@giuliopulina could we close this issue?

**Closed** 2024-02-21 14:53 UTC
Labels: bug
